theme: ./src

siteConfig:
  url: https://fireyy.com
  author: fireyy
  email: fireyy@gmail.com
  title: fireyy
  description: coming soon.

themeConfig:
  social:
    twitter: fireyy
    github: fireyy
    rss: true

plugins:
  - resolve: saber-plugin-query-posts
  - resolve: saber-plugin-feed
    options: 
      atomFeed: true
  - resolve: saber-plugin-prismjs